### ISSUE TITLE
Save file parsing

### ISSUE THREAD

**Issue by TheJaredWilcurt** [dansalvato/melee-gci-compiler#10]
Do you know of any way to parse a Melee save file to get the data out of it in a more human readable manner (like JSON or something)?
If this was possible, then I can make a automated progress tracker for Melee All Trophies (~19 hour speedrun).
I started [some parts of a UI for it](https://thejaredwilcurt.com/melee-all-trophies-tracker), but development stalled with no good ways to source data from the game itself.

**Comment by dansalvato** [comment]
I don't believe such a tool exists, and I'm also not sure if the save file data structure has been fully documented. MGC includes functions to unpack and repack a save file, which can serve as a starting point for anyone interested in fully documenting the format.

For your project specifically, I know tools have been made to communicate GC game data over the network while playing. Your best lead is Slippi, because part of that project includes comprehensive homebrew software that sends Melee game data over the network in realtime. The Slippi team might be able to point you in the right direction if you reach out to them.

Another possible lead is Randovania. Randovania includes a custom build of Nintendont that also sends game memory values over the network in realtime to make auto-trackers and multiworld possible in their randomizers. It could be feasible to modify their work for Melee and send trophy data.

Overall, I think reading game memory is a better approach than parsing the save file, based on the existence of the projects I mentioned. I hope this info helps.
